# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{- $appName        := "bootstrap-rke2-provider" }}
{{- $namespace      := "capr-system" }}
{{- $syncWave       := "1000" }}
---
{{- if (index .Values.argo.enabled $appName) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $syncWave }}"
  name: {{$appName}}
  namespace: {{ required "A valid namespace entry required!" .Values.argo.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ required "A valid projectName entry required!" .Values.argo.project }}
  source:
    repoURL: https://github.com/rancher/cluster-api-provider-rke2
    targetRevision: v0.12.0
    path: bootstrap/config/manager
    kustomize:
      patches:
        - target:
            kind: Deployment
            name: rke2-bootstrap-controller-manager
            namespace: capr-system
          patch: |
            - op: replace
              path: /metadata/name
              value: rke2-bootstrap-controller-manager
            - op: replace
              path: /metadata/namespace
              value: capr-system
            - op: replace
              path: /spec/template/spec/serviceAccountName
              value: rke2-bootstrap-manager
            - op: replace
              path: /spec/template/spec/containers/0/image
              value: ghcr.io/rancher/cluster-api-provider-rke2-bootstrap:v0.12.0
            - op: replace
              path: /spec/template/spec/containers/0/args/1
              value: --diagnostics-address=:8080
            - op: replace
              path: /spec/template/spec/containers/0/args/2
              value: --insecure-diagnostics=true
            - op: replace
              path: /spec/template/spec/containers/0/ports/2
              value:
                containerPort: 8080
                name: metrics
                protocol: TCP
  destination:
    namespace: {{$namespace}}
    server: {{ required "A valid targetServer entry required!" .Values.argo.targetServer }}
  syncPolicy:
    {{- if .Values.argo.autosync }}
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 15
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
{{- end }}
